@url=http://localhost:7000
@api=http://localhost:7000/api
@json=Content-Type: application/json

###
get {{url}}

###
post {{api}}/register
{{json}}

{
    "username": "dada",
    "password": "123456"
}

###
post {{api}}/login
{{json}}

{
    "username": "dada",
    "password": "123456"
}
